### ISSUE TITLE
Id bug

### ISSUE THREAD

**Issue by tchichi** [UCL-INGI/INGInious-problems-blockly#8]
![issue_id](https://user-images.githubusercontent.com/20316317/42276896-c9b37f90-7f95-11e8-8430-cef8f6e14171.png)

No block is shown because when inginious gives an identifier (varid or id) to an argument or variable, it can randomly put a quote character (\`,´, ', ")  as shown in the picture (```<arg name="indice" varid="1%a,twFWP1{DN`^Kr`]E"></arg>```, before and after ^Kr) and makes a bug.
ps: i used the graphical tool to create the blocks

**Comment by ogoletti** [comment]
Hi, 

This issue is no super clear... Inginious does not give any identifier to any block. This is done by bockly. 

What is the workflow ? What were you trying to do ? Is it not shown in the toolbox or on the workspace ?

Can you reproduce this outside of inginious ? I guess the block was created using the blockly factory from the blockly toolbox. Could you share the link to the block ?

**Comment by ogoletti** [comment]
Seems to be linked with https://github.com/google/blockly/issues/682
Try debugging the workspace injection : https://github.com/UCL-INGI/INGInious-problems-blockly/blob/master/inginious-problems-blockly/static/blockly/blockly.js#L119

**Comment by GuillaumeDerval** [comment]
@Maxmawt by which commit was it fixed?

**Comment by Maxmawt** [comment]
The issue is solved with commit fd97f84e4218ead63cbbad6133243ae4628584a2 "Add Xml Support for backpacks"
